"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.
Refactored for Production (Render) + Development (Local).
"""

import os
from pathlib import Path
from dotenv import load_dotenv
import dj_database_url

# Carrega as variáveis de ambiente do arquivo .env
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# --- SEGURANÇA ---

# Pega a chave do .env ou usa uma insegura apenas para dev local
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-kl-f-r10^789!(@8gdo=$kedam7jft%h1gr&cyklx+hzu@s5hk')

# Tenta pegar do .env, se não achar, assume True (Modo Dev)
# Na produção (Render), você deve configurar a variável DEBUG = False
DEBUG = os.getenv('DEBUG', 'True') == 'True'

# Libera acesso para qualquer domínio (necessário para o Render)
ALLOWED_HOSTS = ['*']


# --- APLICAÇÕES ---

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Apps de Terceiros
    'rest_framework',
    'rest_framework.authtoken', # Login via Token
    'corsheaders',              # Conexão com React
    
    # Seus Apps
    'api',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',                   # 1. CORS (Sempre o primeiro)
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',              # 2. Whitenoise (Arquivos estáticos na nuvem)
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# --- BANCO DE DADOS (Híbrido) ---

# Verifica se existe um banco online configurado (Render)
DATABASE_URL = os.getenv("DATABASE_URL")

if DATABASE_URL:
    # Configuração de Produção (PostgreSQL)
    DATABASES = {
        'default': dj_database_url.parse(DATABASE_URL)
    }
else:
    # Configuração Local (SQLite)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# --- VALIDAÇÃO DE SENHA ---

AUTH_PASSWORD_VALIDATORS = [
    { 'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator' },
    { 'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator' },
    { 'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator' },
    { 'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator' },
]


# --- INTERNACIONALIZAÇÃO ---

LANGUAGE_CODE = 'pt-br'        # Mudado para Português
TIME_ZONE = 'America/Sao_Paulo' # Mudado para Horário de Brasília
USE_I18N = True
USE_TZ = True


# --- ARQUIVOS ESTÁTICOS (CSS, JS, Images) ---

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
# Engine otimizada para servir arquivos no Render/Heroku
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


# --- CONFIGURAÇÃO DO CORS (React) ---

# Permite todas as origens (Fácil para dev e Vercel)
# Para maior segurança no futuro, você pode listar apenas o domínio do Vercel
CORS_ALLOW_ALL_ORIGINS = True


# --- CONFIGURAÇÃO DO DRF (API) ---

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
    ],
    # Opcional: Adicionar permissão global se quiser fechar tudo por padrão
    # 'DEFAULT_PERMISSION_CLASSES': [
    #    'rest_framework.permissions.IsAuthenticated',
    # ],
}